/* =============================================
   Offering Collection Management System
   location-config.js — Single Source of Truth
   All categories, aliases, display names, orders.
   ============================================= */

'use strict';

const MASTER_CONFIG = [
  {
    key: 'east_of_kailash',
    displayName: 'East of Kailash',
    summaryOrder: 1,
    inSummary: true,
    inBreakdown: true,
    isParent: false,
    isDynamic: false,
    children: [
      { key: 'east of kailash',  display: 'East of Kailash' },
      { key: 'sant nagar',       display: 'Sant Nagar' },
      { key: 'aya nagar',        display: 'Aya Nagar' },
      { key: 'chhatarpur',       display: 'Chhatarpur' },
      { key: 'mehrauli',         display: 'Mehrauli' },
      { key: 'mahipalpur',       display: 'Mahipalpur' },
      { key: 'malviya nagar',    display: 'Malviya Nagar' },
      { key: 'lado sarai',       display: 'Lado Sarai' },
      { key: 'ber sarai',        display: 'Ber Sarai' },
      { key: 'katwaria sarai',   display: 'Katwaria Sarai' },
      { key: 'sarojini nagar',   display: 'Sarojini Nagar' },
      { key: 'sultanpur',        display: 'Sultanpur' },
      { key: 'sangam vihar',     display: 'Sangam Vihar' },
    ],
    aliases: {
      'iskcon delhi sri sri radha parthasarathi mandir sant nagar': 'east of kailash',
      'sri sri radha parthasarathi mandir': 'east of kailash',
      'radha parthasarathi mandir': 'east of kailash',
      'iskcon east of kailash': 'east of kailash',
      'iskcon sant nagar': 'sant nagar',
      'chattarpur': 'chhatarpur',
      'iskcon chhatarpur': 'chhatarpur',
      'iskcon chattarpur': 'chhatarpur',
      'sarojini nagar centre': 'sarojini nagar',
      'sarojni nagar': 'sarojini nagar',
      'sarojni nagar centre': 'sarojini nagar',
      'iskcon sarojini nagar': 'sarojini nagar',
      'iskcon malviya nagar': 'malviya nagar',
      'iskcon aya nagar': 'aya nagar',
      'iskcon ber sarai': 'ber sarai',
      'iskcon katwaria sarai': 'katwaria sarai',
      'iskcon lado sarai': 'lado sarai',
      'iskcon mahipalpur': 'mahipalpur',
      'iskcon mehrauli': 'mehrauli',
      'iskcon sultanpur': 'sultanpur',
      'iskcon sangam vihar': 'sangam vihar',
    },
  },
  {
    key: 'punjabi_bagh',
    displayName: 'Punjabi Bagh',
    summaryOrder: 2,
    inSummary: true,
    inBreakdown: true,
    isParent: false,
    isDynamic: false,
    children: [
      { key: 'punjabi bagh', display: 'Punjabi Bagh' },
      { key: 'paharganj',    display: 'Paharganj' },
    ],
    aliases: {
      'panjabi bagh': 'punjabi bagh',
      'iskcon punjabi bagh': 'punjabi bagh',
      'iskcon panjabi bagh': 'punjabi bagh',
      'iskcon delhi sri sri radha radhanath mandir punjabi bagh': 'punjabi bagh',
      'sri sri radha radhanath mandir': 'punjabi bagh',
      'radha radhanath mandir': 'punjabi bagh',
      'pahadganj': 'paharganj',
      'iskcon paharganj': 'paharganj',
      'iskcon pahadganj': 'paharganj',
    },
  },
  {
    key: 'rohini',
    displayName: 'Rohini',
    summaryOrder: 3,
    inSummary: true,
    inBreakdown: true,
    isParent: false,
    isDynamic: false,
    children: [
      { key: 'rohini', display: 'Rohini' },
    ],
    aliases: {
      'iskcon rohini': 'rohini',
    },
  },
  {
    key: 'delhi_dwarka',
    displayName: 'Delhi Dwarka',
    summaryOrder: 4,
    inSummary: true,
    inBreakdown: true,
    isParent: false,
    isDynamic: false,
    children: [
      { key: 'dwarka', display: 'Dwarka' },
    ],
    aliases: {
      'dwaraka': 'dwarka',
      'dvaraka': 'dwarka',
      'delhi dwarka': 'dwarka',
      'iskcon dwarka': 'dwarka',
      'iskcon dwaraka': 'dwarka',
      'iskcon dvaraka': 'dwarka',
      'iskcon dwarkadhish': 'dwarka',
    },
  },
  {
    key: 'haryana',
    displayName: 'Haryana',
    summaryOrder: 5,
    inSummary: true,
    inBreakdown: true,
    isParent: true,
    isDynamic: false,
    children: [
      { key: 'faridabad',    display: 'Faridabad' },
      { key: 'gurugram',     display: 'Gurugram' },
      { key: 'badshahpur',   display: 'Badshahpur' },
      { key: 'bahadurgarh',  display: 'Bahadurgarh' },
      { key: 'hisar',        display: 'Hisar' },
      { key: 'kurukshetra',  display: 'Kurukshetra' },
      { key: 'panipat',      display: 'Panipat' },
      { key: 'yamuna nagar', display: 'Yamuna Nagar' },
      { key: 'jhajjar',      display: 'Jhajjar' },
      { key: 'sirsa',        display: 'Sirsa' },
    ],
    aliases: {
      'iskcon faridabad': 'faridabad',
      'shree shree radha govind temple faridabad haryana': 'faridabad',
      'gurgaon': 'gurugram',
      'iskcon gurugram': 'gurugram',
      'iskcon gurgaon': 'gurugram',
      'iskcon badshahpur': 'badshahpur',
      'badshapur': 'badshahpur',
      'iskcon badshapur': 'badshahpur',
      'bhadurgarh': 'bahadurgarh',
      'bahadur garh': 'bahadurgarh',
      'iskcon bahadurgarh': 'bahadurgarh',
      'iskcon bhadurgarh': 'bahadurgarh',
      'hissar': 'hisar',
      'iskcon hisar': 'hisar',
      'iskcon kurukshetra': 'kurukshetra',
      'iskcon panipat': 'panipat',
      'yammuna nagar': 'yamuna nagar',
      'iskcon yamuna nagar': 'yamuna nagar',
      'iskcon yammuna nagar': 'yamuna nagar',
      'iskcon jhajjar': 'jhajjar',
      'iskcon sirsa': 'sirsa',
    },
  },
  {
    key: 'ghaziabad',
    displayName: 'Ghaziabad',
    summaryOrder: 6,
    inSummary: true,
    inBreakdown: true,
    isParent: true,
    isDynamic: false,
    children: [
      { key: 'ghaziabad', display: 'Ghaziabad' },
      { key: 'sahibabad', display: 'Sahibabad' },
    ],
    aliases: {
      'gaziabad': 'ghaziabad',
      'iskcon ghaziabad': 'ghaziabad',
      'iskcon gaziabad': 'ghaziabad',
      'iskcon sahibabad': 'sahibabad',
    },
  },
  {
    key: 'noida',
    displayName: 'Noida',
    summaryOrder: 7,
    inSummary: true,
    inBreakdown: true,
    isParent: false,
    isDynamic: false,
    children: [
      { key: 'noida', display: 'Noida' },
    ],
    aliases: {
      'iskcon noida': 'noida',
    },
  },
  {
    key: 'chhipiwada',
    displayName: 'Chhipiwada',
    summaryOrder: 8,
    inSummary: true,
    inBreakdown: true,
    isParent: false,
    isDynamic: false,
    children: [
      { key: 'chhipiwada', display: 'Chhipiwada' },
    ],
    aliases: {
      'chippiwara': 'chhipiwada',
      'chhipiwara': 'chhipiwada',
      'chippiwada': 'chhipiwada',
      'chhippiwada': 'chhipiwada',
      'iskcon chippiwara': 'chhipiwada',
      'iskcon chippiwada': 'chhipiwada',
      'iskcon chhipiwada': 'chhipiwada',
      'iskcon chhipiwara': 'chhipiwada',
      'iskcon chhippiwada': 'chhipiwada',
    },
  },
  {
    key: 'outside',
    displayName: 'Outside Delhi / Haryana / NCR',
    summaryOrder: 9,
    inSummary: true,
    inBreakdown: true,
    isParent: true,
    isDynamic: true, // children discovered at runtime
    children: [],
    aliases: {
      // Known outside locations — clean canonical display names
      'mumbai juhu': 'mumbai (juhu)',
      'mumbai(juhu)': 'mumbai (juhu)',
      'iskcon mumbai juhu': 'mumbai (juhu)',
      'iskcon mumbai(juhu)': 'mumbai (juhu)',
      'iskcon mumbai (juhu)': 'mumbai (juhu)',
      'navi mumbai': 'kharghar',
      'navi mumbai kharghar': 'kharghar',
      'mumbai kharghar': 'kharghar',
      'iskcon kharghar': 'kharghar',
      'iskcon navi mumbai': 'kharghar',
      'kharghar': 'kharghar',
      'iskcon ahmedabad': 'ahmedabad',
      'iskcon ahmedabad satellite': 'ahmedabad',
      'satellite': 'ahmedabad',
      'iskcon satellite': 'ahmedabad',
      'sri sri radha madana mohan satellite': 'ahmedabad',
      'radha madana mohan': 'ahmedabad',
      'iskcon of boston': 'boston',
      'new gundica temple': 'boston',
      'new gundica': 'boston',
      'iskcon boston': 'boston',
      'iskcon atlanta': 'atlanta',
      'iskcon detroit': 'detroit',
      'devasadan': 'devasadan mandir',
      'allahabad': 'prayagraj',
      'iskcon prayagraj': 'prayagraj',
      'iskcon vrindavan': 'vrindavan',
      'bgis vrindavan': 'vrindavan',
      'iskcon sravan keertana bhavan tadepalligudem': 'tadepalligudem',
      'sravan keertana bhavan tadepalligudem': 'tadepalligudem',
      'sravan keertana bhavan': 'tadepalligudem',
      'iskcon tadepalligudem': 'tadepalligudem',
      'whitefiled': 'whitefield',
      'iskcon whitefield': 'whitefield',
      'iskcon thrissur': 'thrissur',
      'iskcon pali': 'pali',
      'pali rajasthan': 'pali',
      'iskcon chandigarh': 'chandigarh',
      'iskcon jaipur': 'jaipur',
      'iskcon kolkata': 'kolkata',
      'iskcon pune': 'pune',
      'pune nvcc': 'pune nvcc',
      'iskcon surat': 'surat',
      'iskcon indore': 'indore',
      'iskcon bhopal': 'bhopal',
      'iskcon varanasi': 'varanasi',
      'iskcon dehradun': 'dehradun',
      'iskcon jalandhar': 'jalandhar',
      'iskcon amritsar': 'amritsar',
      'iskcon ludhiana': 'ludhiana',
      'iskcon meerut': 'meerut',
      'iskcon kanpur': 'kanpur',
      'iskcon hyderabad': 'hyderabad',
      'iskcon chennai': 'chennai',
      'iskcon coimbatore': 'coimbatore',
      'iskcon jodhpur': 'jodhpur',
      'iskcon patna': 'patna',
      'iskcon kangra': 'kangra',
      'iskcon rudrapur': 'rudrapur',
      'baroda': 'vadodara',
      'iskcon baroda': 'vadodara',
      'iskcon vadodara': 'vadodara',
      'iskcon ponda': 'ponda',
      'iskcon mayapur': 'mayapur',
      'iskcon jajpur': 'jajpur',
    },
  },
  {
    key: 'unknown',
    displayName: 'Unknown',
    summaryOrder: 10,
    inSummary: true,
    inBreakdown: true,
    isParent: true,
    isDynamic: false,
    children: [
      { key: 'unknown', display: 'Unknown' },
      { key: 'none',    display: 'None' },
      { key: 'no',      display: 'No' },
      { key: 'blank',   display: 'Blank' },
      { key: 'empty',   display: 'Empty' },
      { key: 'null',    display: 'NULL' },
      { key: '-',       display: '-' },
      { key: 'na',      display: 'N/A' },
    ],
    aliases: {
      'n/a': 'na',
      'n.a.': 'na',
      'nil': 'none',
      'nill': 'none',
    },
  },
];

// Validation: ensure no child key appears in multiple categories
(function validateConfig() {
  const seen = new Map();
  for (const cat of MASTER_CONFIG) {
    for (const child of cat.children) {
      if (seen.has(child.key)) {
        console.warn(`[CONFIG] Duplicate child key "${child.key}" in "${cat.key}" and "${seen.get(child.key)}"`);
      }
      seen.set(child.key, cat.key);
    }
  }
})();
